// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ServerConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"` // effective configuration (defaults resolved)
	Services      []*ServiceBucket       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StatsResponse) GetServices() []*ServiceBucket {
	if x != nil {
		return x.Services
	}
	return nil
}

// ServiceBucket represents one top-level bbolt bucket (one per service name).
type ServiceBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Months        []*MonthBucket         `protobuf:"bytes,2,rep,name=months,proto3" json:"months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceBucket) Reset() {
	*x = ServiceBucket{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBucket) ProtoMessage() {}

func (x *ServiceBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBucket.ProtoReflect.Descriptor instead.
func (*ServiceBucket) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceBucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceBucket) GetMonths() []*MonthBucket {
	if x != nil {
		return x.Months
	}
	return nil
}

// MonthBucket represents one nested bbolt bucket (one per YYYY-MM).
type MonthBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`                           // YYYY-MM
	SpanCount     int64                  `protobuf:"varint,2,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"` // number of span entries in this bucket
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthBucket) Reset() {
	*x = MonthBucket{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthBucket) ProtoMessage() {}

func (x *MonthBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthBucket.ProtoReflect.Descriptor instead.
func (*MonthBucket) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *MonthBucket) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthBucket) GetSpanCount() int64 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

type GetSpansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // max entries to return; 0 defaults to 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpansRequest) Reset() {
	*x = GetSpansRequest{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpansRequest) ProtoMessage() {}

func (x *GetSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpansRequest.ProtoReflect.Descriptor instead.
func (*GetSpansRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetSpansRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetSpansRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SpanEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // hex-encoded
	SpanId            string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`    // hex-encoded
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Month             string                 `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"` // YYYY-MM bucket the entry lives in
	StartTimeUnixNano int64                  `protobuf:"varint,5,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano   int64                  `protobuf:"varint,6,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	StatusCode        int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ParentSpanId      string                 `protobuf:"bytes,8,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"` // hex-encoded; empty for root spans
	SpanProto         []byte                 `protobuf:"bytes,9,opt,name=span_proto,json=spanProto,proto3" json:"span_proto,omitempty"`            // serialized opentelemetry.proto.trace.v1.Span
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpanEntry) Reset() {
	*x = SpanEntry{}
	mi := &file_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanEntry) ProtoMessage() {}

func (x *SpanEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanEntry.ProtoReflect.Descriptor instead.
func (*SpanEntry) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *SpanEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SpanEntry) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *SpanEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpanEntry) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *SpanEntry) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *SpanEntry) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *SpanEntry) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SpanEntry) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *SpanEntry) GetSpanProto() []byte {
	if x != nil {
		return x.SpanProto
	}
	return nil
}

type GetSpansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Spans         []*SpanEntry           `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpansResponse) Reset() {
	*x = GetSpansResponse{}
	mi := &file_proto_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpansResponse) ProtoMessage() {}

func (x *GetSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpansResponse.ProtoReflect.Descriptor instead.
func (*GetSpansResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpansResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetSpansResponse) GetSpans() []*SpanEntry {
	if x != nil {
		return x.Spans
	}
	return nil
}

type GetSpanTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanId        string                 `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"` // hex-encoded span_id of any span in the trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpanTreeRequest) Reset() {
	*x = GetSpanTreeRequest{}
	mi := &file_proto_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpanTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpanTreeRequest) ProtoMessage() {}

func (x *GetSpanTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpanTreeRequest.ProtoReflect.Descriptor instead.
func (*GetSpanTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *GetSpanTreeRequest) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

type GetTraceByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // hex-encoded trace ID to look up
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceByIDRequest) Reset() {
	*x = GetTraceByIDRequest{}
	mi := &file_proto_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceByIDRequest) ProtoMessage() {}

func (x *GetTraceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTraceByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{8}
}

func (x *GetTraceByIDRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// GetSpanTreeResponse contains all spans that share the same trace_id as the
// requested span and whose start time falls within ±2 minutes of that span.
type GetSpanTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Spans         []*SpanEntry           `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpanTreeResponse) Reset() {
	*x = GetSpanTreeResponse{}
	mi := &file_proto_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpanTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpanTreeResponse) ProtoMessage() {}

func (x *GetSpanTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpanTreeResponse.ProtoReflect.Descriptor instead.
func (*GetSpanTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{9}
}

func (x *GetSpanTreeResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetSpanTreeResponse) GetSpans() []*SpanEntry {
	if x != nil {
		return x.Spans
	}
	return nil
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // service name to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_proto_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteServiceRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_proto_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{11}
}

type GetTraceIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // max trace IDs to return; 0 defaults to 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceIDsRequest) Reset() {
	*x = GetTraceIDsRequest{}
	mi := &file_proto_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceIDsRequest) ProtoMessage() {}

func (x *GetTraceIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceIDsRequest.ProtoReflect.Descriptor instead.
func (*GetTraceIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{12}
}

func (x *GetTraceIDsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetTraceIDsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTraceIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	TraceIds      []string               `protobuf:"bytes,2,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"` // hex-encoded trace IDs, newest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceIDsResponse) Reset() {
	*x = GetTraceIDsResponse{}
	mi := &file_proto_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceIDsResponse) ProtoMessage() {}

func (x *GetTraceIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceIDsResponse.ProtoReflect.Descriptor instead.
func (*GetTraceIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{13}
}

func (x *GetTraceIDsResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetTraceIDsResponse) GetTraceIds() []string {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_proto_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{14}
}

// ServiceSummary holds per-service aggregate statistics.
type ServiceSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TraceCount          int64                  `protobuf:"varint,2,opt,name=trace_count,json=traceCount,proto3" json:"trace_count,omitempty"`                                // distinct trace IDs across all stored spans
	SpanCount           int64                  `protobuf:"varint,3,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"`                                   // total stored spans
	LastUpdatedUnixNano int64                  `protobuf:"varint,4,opt,name=last_updated_unix_nano,json=lastUpdatedUnixNano,proto3" json:"last_updated_unix_nano,omitempty"` // start time of the most recently stored span
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceSummary) Reset() {
	*x = ServiceSummary{}
	mi := &file_proto_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSummary) ProtoMessage() {}

func (x *ServiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSummary.ProtoReflect.Descriptor instead.
func (*ServiceSummary) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{15}
}

func (x *ServiceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSummary) GetTraceCount() int64 {
	if x != nil {
		return x.TraceCount
	}
	return 0
}

func (x *ServiceSummary) GetSpanCount() int64 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

func (x *ServiceSummary) GetLastUpdatedUnixNano() int64 {
	if x != nil {
		return x.LastUpdatedUnixNano
	}
	return 0
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceSummary      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_proto_stats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceSummary {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\botelstor\x1a\x12proto/config.proto\"\x0e\n" +
	"\fStatsRequest\"t\n" +
	"\rStatsResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.otelstor.ServerConfigR\x06config\x123\n" +
	"\bservices\x18\x02 \x03(\v2\x17.otelstor.ServiceBucketR\bservices\"R\n" +
	"\rServiceBucket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x06months\x18\x02 \x03(\v2\x15.otelstor.MonthBucketR\x06months\"B\n" +
	"\vMonthBucket\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"span_count\x18\x02 \x01(\x03R\tspanCount\"A\n" +
	"\x0fGetSpansRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xad\x02\n" +
	"\tSpanEntry\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05month\x18\x04 \x01(\tR\x05month\x12/\n" +
	"\x14start_time_unix_nano\x18\x05 \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\x06 \x01(\x03R\x0fendTimeUnixNano\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12$\n" +
	"\x0eparent_span_id\x18\b \x01(\tR\fparentSpanId\x12\x1d\n" +
	"\n" +
	"span_proto\x18\t \x01(\fR\tspanProto\"W\n" +
	"\x10GetSpansResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12)\n" +
	"\x05spans\x18\x02 \x03(\v2\x13.otelstor.SpanEntryR\x05spans\"-\n" +
	"\x12GetSpanTreeRequest\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\"0\n" +
	"\x13GetTraceByIDRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"[\n" +
	"\x13GetSpanTreeResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12)\n" +
	"\x05spans\x18\x02 \x03(\v2\x13.otelstor.SpanEntryR\x05spans\"0\n" +
	"\x14DeleteServiceRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x17\n" +
	"\x15DeleteServiceResponse\"D\n" +
	"\x12GetTraceIDsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x13GetTraceIDsResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1b\n" +
	"\ttrace_ids\x18\x02 \x03(\tR\btraceIds\"\x15\n" +
	"\x13ListServicesRequest\"\x99\x01\n" +
	"\x0eServiceSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vtrace_count\x18\x02 \x01(\x03R\n" +
	"traceCount\x12\x1d\n" +
	"\n" +
	"span_count\x18\x03 \x01(\x03R\tspanCount\x123\n" +
	"\x16last_updated_unix_nano\x18\x04 \x01(\x03R\x13lastUpdatedUnixNano\"L\n" +
	"\x14ListServicesResponse\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.otelstor.ServiceSummaryR\bservices2\x95\x04\n" +
	"\fStatsService\x12;\n" +
	"\bGetStats\x12\x16.otelstor.StatsRequest\x1a\x17.otelstor.StatsResponse\x12A\n" +
	"\bGetSpans\x12\x19.otelstor.GetSpansRequest\x1a\x1a.otelstor.GetSpansResponse\x12J\n" +
	"\vGetSpanTree\x12\x1c.otelstor.GetSpanTreeRequest\x1a\x1d.otelstor.GetSpanTreeResponse\x12P\n" +
	"\rDeleteService\x12\x1e.otelstor.DeleteServiceRequest\x1a\x1f.otelstor.DeleteServiceResponse\x12J\n" +
	"\vGetTraceIDs\x12\x1c.otelstor.GetTraceIDsRequest\x1a\x1d.otelstor.GetTraceIDsResponse\x12M\n" +
	"\fListServices\x12\x1d.otelstor.ListServicesRequest\x1a\x1e.otelstor.ListServicesResponse\x12L\n" +
	"\fGetTraceByID\x12\x1d.otelstor.GetTraceByIDRequest\x1a\x1d.otelstor.GetSpanTreeResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_stats_proto_goTypes = []any{
	(*StatsRequest)(nil),          // 0: otelstor.StatsRequest
	(*StatsResponse)(nil),         // 1: otelstor.StatsResponse
	(*ServiceBucket)(nil),         // 2: otelstor.ServiceBucket
	(*MonthBucket)(nil),           // 3: otelstor.MonthBucket
	(*GetSpansRequest)(nil),       // 4: otelstor.GetSpansRequest
	(*SpanEntry)(nil),             // 5: otelstor.SpanEntry
	(*GetSpansResponse)(nil),      // 6: otelstor.GetSpansResponse
	(*GetSpanTreeRequest)(nil),    // 7: otelstor.GetSpanTreeRequest
	(*GetTraceByIDRequest)(nil),   // 8: otelstor.GetTraceByIDRequest
	(*GetSpanTreeResponse)(nil),   // 9: otelstor.GetSpanTreeResponse
	(*DeleteServiceRequest)(nil),  // 10: otelstor.DeleteServiceRequest
	(*DeleteServiceResponse)(nil), // 11: otelstor.DeleteServiceResponse
	(*GetTraceIDsRequest)(nil),    // 12: otelstor.GetTraceIDsRequest
	(*GetTraceIDsResponse)(nil),   // 13: otelstor.GetTraceIDsResponse
	(*ListServicesRequest)(nil),   // 14: otelstor.ListServicesRequest
	(*ServiceSummary)(nil),        // 15: otelstor.ServiceSummary
	(*ListServicesResponse)(nil),  // 16: otelstor.ListServicesResponse
	(*ServerConfig)(nil),          // 17: otelstor.ServerConfig
}
var file_proto_stats_proto_depIdxs = []int32{
	17, // 0: otelstor.StatsResponse.config:type_name -> otelstor.ServerConfig
	2,  // 1: otelstor.StatsResponse.services:type_name -> otelstor.ServiceBucket
	3,  // 2: otelstor.ServiceBucket.months:type_name -> otelstor.MonthBucket
	5,  // 3: otelstor.GetSpansResponse.spans:type_name -> otelstor.SpanEntry
	5,  // 4: otelstor.GetSpanTreeResponse.spans:type_name -> otelstor.SpanEntry
	15, // 5: otelstor.ListServicesResponse.services:type_name -> otelstor.ServiceSummary
	0,  // 6: otelstor.StatsService.GetStats:input_type -> otelstor.StatsRequest
	4,  // 7: otelstor.StatsService.GetSpans:input_type -> otelstor.GetSpansRequest
	7,  // 8: otelstor.StatsService.GetSpanTree:input_type -> otelstor.GetSpanTreeRequest
	10, // 9: otelstor.StatsService.DeleteService:input_type -> otelstor.DeleteServiceRequest
	12, // 10: otelstor.StatsService.GetTraceIDs:input_type -> otelstor.GetTraceIDsRequest
	14, // 11: otelstor.StatsService.ListServices:input_type -> otelstor.ListServicesRequest
	8,  // 12: otelstor.StatsService.GetTraceByID:input_type -> otelstor.GetTraceByIDRequest
	1,  // 13: otelstor.StatsService.GetStats:output_type -> otelstor.StatsResponse
	6,  // 14: otelstor.StatsService.GetSpans:output_type -> otelstor.GetSpansResponse
	9,  // 15: otelstor.StatsService.GetSpanTree:output_type -> otelstor.GetSpanTreeResponse
	11, // 16: otelstor.StatsService.DeleteService:output_type -> otelstor.DeleteServiceResponse
	13, // 17: otelstor.StatsService.GetTraceIDs:output_type -> otelstor.GetTraceIDsResponse
	16, // 18: otelstor.StatsService.ListServices:output_type -> otelstor.ListServicesResponse
	9,  // 19: otelstor.StatsService.GetTraceByID:output_type -> otelstor.GetSpanTreeResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	file_proto_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
